global:
  # Global configuration
  smtp_smarthost: 'localhost:587'
  smtp_from: 'veogen-alerts@yourdomain.com'
  smtp_auth_username: 'veogen-alerts@yourdomain.com'
  smtp_auth_password: 'your-email-password'

# Templates for notifications
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Route tree
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default-receiver'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 0s
      repeat_interval: 5m
    - match:
        severity: warning
      receiver: 'warning-alerts'
      repeat_interval: 30m
    - match:
        severity: info
      receiver: 'info-alerts'
      repeat_interval: 4h

# Receivers define how to send notifications
receivers:
  - name: 'default-receiver'
    webhook_configs:
      - url: 'http://backend:8000/api/v1/alerts/webhook'
        send_resolved: true
        http_config:
          bearer_token: 'your-webhook-token'

  - name: 'critical-alerts'
    email_configs:
      - to: 'admin@yourdomain.com'
        headers:
          subject: 'CRITICAL: VeoGen Alert - {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Service: {{ .Labels.service }}
          Severity: {{ .Labels.severity }}
          Started: {{ .StartsAt }}
          {{ end }}
#    slack_configs:
#      - api_url: 'YOUR_SLACK_WEBHOOK_URL'
#        channel: '#veogen-alerts'
#        title: 'CRITICAL VeoGen Alert'
#        text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
#        color: 'danger'

  - name: 'warning-alerts'
    email_configs:
      - to: 'team@yourdomain.com'
        headers:
          subject: 'WARNING: VeoGen Alert - {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Service: {{ .Labels.service }}
          Severity: {{ .Labels.severity }}
          Started: {{ .StartsAt }}
          {{ end }}
#    slack_configs:
#      - api_url: 'YOUR_SLACK_WEBHOOK_URL'
#        channel: '#veogen-warnings'
#        title: 'VeoGen Warning'
#        text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
#        color: 'warning'

  - name: 'info-alerts'
#    slack_configs:
#      - api_url: 'YOUR_SLACK_WEBHOOK_URL'
#        channel: '#veogen-info'
#        title: 'VeoGen Info'
#        text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
#        color: 'good'

# Inhibition rules
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']
